services:
  new-seasons-reminder:
    image: reminder
    environment:
      - SOURCE_TYPE=tautulli
      - TAUTULLI_URL=https://stats.fk.h-cloud.io
      - TAUTULLI_APIKEY=cutyM-FGaX2soesmEeJxNcIHmsa7i8g_
      - WEBHOOK_URL=https://wh.ut.h-cloud.lan/v1/plugins/seerr-notification
      - INCLUDE_NEW_SHOWS=true
      - LOOKBACK_DAYS=60
      - SIGNAL_RECIPIENTS=group.eEx1M01adTlpYmJCSnBrWlVENm5YOGQvSHM1RTAvOExhR3FNY3luUzNYbz0=
      - SIGNAL_NUMBER=+4915224899477
      - WEBHOOK_MODE=signal-cli
      - DEBUG=true
      - DISABLE_SSL_VERIFY=true
    restart: no
