name: Renovate

on:
  schedule:
    - cron: '0 6 * * 0'
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Run Renovate
        uses: renovatebot/github-action@v46.1.5
        with:
          renovate-version: latest
        env:
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_SECRET }}
          GITHUB_COM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          LOG_LEVEL: debug
